# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce68e9ae386256bc94c89744e649c5986b77a943b6dc0e47f60e6d5ce35273fe1275d1855a533b56b0c9b4f15b5cf01d19ddcaa1d8a83f7714d9c51421847a5e

test:
  secret_key_base: d5c567fa6a8eff00b31dd9a7156b35ced16f0897a185773f59f1f2ce2a497deb56d102d9323378975043aac4a0f4ccf6bb8ce98cb2243b3cab76e8d9688f8c13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
